# SPDX-License-Identifier: GPL-3.0-or-later
"""Extract the original's pathfinding **route streams** from SCRANTIC.EXE and emit them as a
Rust data table (the faithful replacement for the jc_reborn-reconstructed WALK_MATRIX).

Format (reverse-engineered — see ../knowledge-base/10 §10.3):
  - 6×6 word-pointer table, lookup `*(0x0A94 + start*12 + dest*2)`, spots 1-based (0 = diagonal).
  - each pointer → a stream of sections: a negative marker `-N` starts the section for
    "cursor at spot N"; then `(value, weight)` u16 pairs until the next marker; `-7` ends it.
  - a `value` → 3-byte record at `0x02DE + value*3` = `(start_heading, end_heading, next_spot)`.
  So section `-N` lists, for cursor spot N, the weighted choices of `next_spot` (weights/100).

Inputs (env): SCRANTIC_EXE (default ./SCRANTIC.EXE). The binary is copyright and stays local;
this script only emits decoded route facts (like walk_data). Prints a human summary and writes
a Rust module to stdout's companion file via --rust.
"""
import os
import sys
import struct

PATH = os.environ.get("SCRANTIC_EXE", "SCRANTIC.EXE")
D = open(PATH, "rb").read()
BASE = 0x17E00            # seg14 (DATA) file base: file = BASE + seg14_virtual_offset
TABLE = 0x0A94           # lookup base (virtual): *(TABLE + start*12 + dest*2)
RECORDS = 0x02DE         # 3-byte (start_hdg, end_hdg, next_spot) records, indexed by value*3


def u16(vaddr):
    o = BASE + vaddr
    return D[o] | (D[o + 1] << 8)


def i16(vaddr):
    v = u16(vaddr)
    return v - 0x10000 if v >= 0x8000 else v


def next_spot(value):
    """The destination spot (1-based) a `value` move walks to (record byte 2)."""
    o = BASE + RECORDS + value * 3
    return D[o + 2]


def decode_stream(ptr):
    """Decode the stream at virtual offset `ptr` into {cursor_spot: [(next_spot, weight)]}."""
    sections = {}
    v = ptr
    cur = None
    while True:
        w = i16(v)
        v += 2
        if w < 0:
            if w == -7:
                break
            cur = -w                      # start the section for "cursor at spot -w"
            sections.setdefault(cur, [])
        else:
            weight = i16(v)
            v += 2
            if cur is not None and not (w == 0 and weight == 0):
                sections[cur].append((next_spot(w), weight))
    return sections


def table_ptr(start, dest):
    return u16(TABLE + start * 12 + dest * 2)


def all_streams():
    out = {}
    for start in range(1, 7):
        for dest in range(1, 7):
            if start == dest:
                continue
            ptr = table_ptr(start, dest)
            if ptr == 0:
                continue
            out[(start, dest)] = decode_stream(ptr)
    return out


def enumerate_routes(start, dest, sections):
    """All simple routes start→dest by following the section choices (for verification)."""
    routes = []

    def walk(cur, path, seen):
        if cur == dest:
            routes.append(tuple(path))
            return
        for nxt, _w in sections.get(cur, []):
            if nxt in seen:
                continue
            walk(nxt, path + [nxt], seen | {nxt})

    walk(start, [start], {start})
    # de-dup while keeping order
    uniq = []
    for r in routes:
        if r not in uniq:
            uniq.append(r)
    return uniq


if __name__ == "__main__":
    streams = all_streams()
    print(f"# decoded {len(streams)} route streams (expected 30)\n", file=sys.stderr)

    # Verification summary (compare to the RE report): per pair, the section directly at
    # `start` must exist (confirms the from-index direction), and the enumerated routes.
    for (s, d), sec in sorted(streams.items()):
        has_start = s in sec
        routes = enumerate_routes(s, d, sec)
        rs = " ".join("".join(str(x) for x in r) for r in routes)
        flag = "" if has_start else "  <<< no section for start!"
        print(f"s{s}->d{d}: {rs}{flag}", file=sys.stderr)

    if "--rust" in sys.argv:
        # Emit ROUTE_STREAMS[from][to] as 0-based Rust: each cell is a slice of
        # (cursor, &[(next, weight)]) sections.
        print("// @generated by docs/reverse-engineering/extract_calcpath.py — do not edit by hand.")
        print("// SPDX-License-Identifier: GPL-3.0-or-later")
        print("//! The original's pathfinding route streams (extracted from SCRANTIC.EXE).")
        print("//! `ROUTE_STREAMS[from][to]` lists, per cursor spot, the weighted next-spot")
        print("//! choices (weights sum to 100). Spots are 0-based (A=0..F=5). See KB10 §10.3.")
        print("\n/// One cursor's weighted moves: `(cursor_spot, &[(next_spot, weight)])`.")
        print("pub type Section = (u8, &'static [(u8, u8)]);")
        print("\n// Long generated rows; keep them verbatim (and reproducible) rather than rewrapped.")
        print("#[rustfmt::skip]")
        print("pub static ROUTE_STREAMS: [[&[Section]; 6]; 6] = [")
        for s in range(6):
            print("    [")
            for d in range(6):
                sec = streams.get((s + 1, d + 1))
                if not sec:
                    print("        &[],")
                    continue
                parts = []
                for cur in sorted(sec):
                    moves = ", ".join(f"({n-1}, {w})" for n, w in sec[cur])
                    parts.append(f"({cur-1}, &[{moves}])")
                print(f"        &[{', '.join(parts)}],")
            print("    ],")
        print("];")
