// SPDX-License-Identifier: GPL-3.0-or-later
//! When the optional `embed-data` feature is enabled, embed the user's original Johnny
//! Castaway data (pointed at by `WILSON_EMBED_DATA`) into the binary, producing a
//! self-contained build. The data is read only at build time from the local path — it
//! is never written into the repository.

use std::{env, fs, path::Path};

fn main() {
    println!("cargo:rerun-if-env-changed=WILSON_EMBED_DATA");

    // Only do anything when the `embed-data` feature is on (Cargo sets this env var).
    if env::var_os("CARGO_FEATURE_EMBED_DATA").is_none() {
        return;
    }

    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("embedded_data.rs");

    // The feature can be enabled without data (e.g. CI's `--all-features`). Emit a
    // compilable stub + a warning so the build still succeeds; the resulting binary
    // just won't run until built with WILSON_EMBED_DATA pointing at real data.
    let Some(dir) = env::var_os("WILSON_EMBED_DATA") else {
        println!(
            "cargo:warning=feature `embed-data` is enabled but WILSON_EMBED_DATA is unset; \
             building a stub (this binary will NOT run). Set WILSON_EMBED_DATA to embed the \
             original RESOURCE.* + soundN.wav."
        );
        fs::write(
            &out,
            "pub static MAP: &[u8] = &[];\npub static DATA: &[u8] = &[];\n\
             pub static SOUNDS: &[(u16, &[u8])] = &[];\n",
        )
        .expect("write embedded_data.rs stub");
        return;
    };
    let dir = Path::new(&dir);
    println!("cargo:rerun-if-changed={}", dir.display());

    let map_path = dir.join("RESOURCE.MAP");
    let map = fs::read(&map_path)
        .unwrap_or_else(|e| panic!("WILSON_EMBED_DATA: cannot read {}: {e}", map_path.display()));

    // RESOURCE.MAP: 6 unknown bytes, then a 13-byte NUL-padded data file name.
    let data_name: String = map
        .get(6..19)
        .map(|n| {
            n.iter()
                .take_while(|&&b| b != 0)
                .map(|&b| b as char)
                .collect()
        })
        .filter(|s: &String| !s.is_empty())
        .unwrap_or_else(|| "RESOURCE.001".to_string());
    let data_path = dir.join(&data_name);
    assert!(
        data_path.is_file(),
        "WILSON_EMBED_DATA: data file {} (named by RESOURCE.MAP) not found",
        data_path.display()
    );

    // Embed whichever soundN.wav are present (0..=24; the originals skip 11 and 13).
    let mut entries: Vec<(u16, std::path::PathBuf)> = Vec::new();
    for id in 0u16..25 {
        let wav = dir.join(format!("sound{id}.wav"));
        if wav.is_file() {
            entries.push((id, wav));
        }
    }
    // Fallback: no soundN.wav supplied (e.g. the original scrantic-run distribution) — the
    // effects are embedded as WAVs in SCRANTIC.EXE/.SCR. Extract them to OUT_DIR and embed.
    if entries.is_empty() {
        let out_parent = Path::new(&out).parent().unwrap().to_path_buf();
        for exe in ["SCRANTIC.EXE", "SCRANTIC.SCR"] {
            let Ok(bytes) = fs::read(dir.join(exe)) else {
                continue;
            };
            let sounds = wilson_dgds::sounds_from_scrantic_exe(&bytes);
            if sounds.iter().any(Option::is_some) {
                for (id, slot) in sounds.iter().enumerate() {
                    if let Some(wav) = slot {
                        let path = out_parent.join(format!("sound{id}.wav"));
                        fs::write(&path, wav).expect("write extracted soundN.wav");
                        entries.push((id as u16, path));
                    }
                }
                break;
            }
        }
    }
    let mut sounds = String::from("&[");
    for (id, path) in &entries {
        sounds.push_str(&format!(
            "({id}, include_bytes!(r\"{}\")), ",
            path.display()
        ));
    }
    sounds.push(']');

    let code = format!(
        "// @generated by build.rs — embedded original data.\n\
         pub static MAP: &[u8] = include_bytes!(r\"{}\");\n\
         pub static DATA: &[u8] = include_bytes!(r\"{}\");\n\
         pub static SOUNDS: &[(u16, &[u8])] = {};\n",
        map_path.display(),
        data_path.display(),
        sounds,
    );
    fs::write(&out, code).expect("write embedded_data.rs");
}
