// SPDX-License-Identifier: GPL-3.0-or-later
//! Build script for `wilson-web`.
//!
//! Only does something for the `embed-data` feature: bake the user's original data
//! (`WILSON_EMBED_DATA`) into the wasm for a self-contained, file-picker-free page — the
//! `RESOURCE.*` plus the sound effects (the WAVs embedded in `SCRANTIC.EXE`). The data is read
//! only at build time from the local path and is NEVER written into the repository. (Mirrors
//! the desktop `wilson` crate's embed.)

use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn main() {
    println!("cargo:rerun-if-env-changed=WILSON_EMBED_DATA");
    if env::var_os("CARGO_FEATURE_EMBED_DATA").is_some() {
        embed_data();
    }
}

fn embed_data() {
    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("embedded_data.rs");

    // The feature can be enabled without data (e.g. CI). Emit a compilable stub + a warning
    // so the build still succeeds; the resulting page just won't have data baked in.
    let Some(dir) = env::var_os("WILSON_EMBED_DATA") else {
        println!(
            "cargo:warning=feature `embed-data` is enabled but WILSON_EMBED_DATA is unset; \
             building a stub (no data baked in). Set WILSON_EMBED_DATA to embed RESOURCE.*."
        );
        fs::write(
            &out,
            "pub static MAP: &[u8] = &[];\npub static DATA: &[u8] = &[];\n\
             pub static SOUNDS: &[(u16, &[u8])] = &[];\n",
        )
        .expect("write embedded_data.rs stub");
        return;
    };
    let dir = Path::new(&dir);
    println!("cargo:rerun-if-changed={}", dir.display());

    let map_path = dir.join("RESOURCE.MAP");
    let map = fs::read(&map_path)
        .unwrap_or_else(|e| panic!("WILSON_EMBED_DATA: cannot read {}: {e}", map_path.display()));

    // RESOURCE.MAP: 6 unknown bytes, then a 13-byte NUL-padded data file name.
    let data_name: String = map
        .get(6..19)
        .map(|n| {
            n.iter()
                .take_while(|&&b| b != 0)
                .map(|&b| b as char)
                .collect()
        })
        .filter(|s: &String| !s.is_empty())
        .unwrap_or_else(|| "RESOURCE.001".to_string());

    // Normally RESOURCE.001 sits next to the MAP; the original *installer* stores it
    // compressed as RESOURCE.00$ — decompress that on the fly into OUT_DIR.
    let named = dir.join(&data_name);
    let data_path = if named.is_file() && fs::metadata(&named).map(|m| m.len()).unwrap_or(0) > 1000
    {
        named
    } else if let Ok(comp) = fs::read(dir.join("RESOURCE.00$")) {
        let data = wilson_dgds::decompress_installer(&comp)
            .expect("WILSON_EMBED_DATA: RESOURCE.00$ present but could not be decompressed");
        let p = Path::new(&out).parent().unwrap().join("RESOURCE.001");
        fs::write(&p, &data).expect("write decompressed RESOURCE.001");
        p
    } else {
        panic!(
            "WILSON_EMBED_DATA: data file {} not found (and no RESOURCE.00$ installer file)",
            named.display()
        );
    };

    // Sound effects: prefer soundN.wav on disk, else extract the WAVs embedded in
    // SCRANTIC.EXE/.SCR (or the installer's compressed SCRANTIC.SC$), like the desktop build.
    // Written to OUT_DIR and include_bytes!'d. Absent data ⇒ no SOUNDS ⇒ a silent (but valid)
    // build. The web is otherwise silent without this.
    let out_parent = Path::new(&out).parent().unwrap().to_path_buf();
    let mut sounds: Vec<(u16, PathBuf)> = Vec::new();
    for id in 0u16..25 {
        let wav = dir.join(format!("sound{id}.wav"));
        if wav.is_file() {
            sounds.push((id, wav));
        }
    }
    if sounds.is_empty() {
        let exe = ["SCRANTIC.EXE", "SCRANTIC.SCR"]
            .iter()
            .find_map(|n| fs::read(dir.join(n)).ok())
            .or_else(|| {
                fs::read(dir.join("SCRANTIC.SC$"))
                    .ok()
                    .and_then(|c| wilson_dgds::decompress_installer(&c))
            });
        if let Some(bytes) = exe {
            for (id, slot) in wilson_dgds::sounds_from_scrantic_exe(&bytes)
                .iter()
                .enumerate()
            {
                if let Some(wav) = slot {
                    let path = out_parent.join(format!("sound{id}.wav"));
                    fs::write(&path, wav).expect("write extracted soundN.wav");
                    sounds.push((id as u16, path));
                }
            }
        }
    }
    if sounds.is_empty() {
        println!(
            "cargo:warning=WILSON_EMBED_DATA has no soundN.wav and no SCRANTIC.EXE/.SCR/.SC$ — \
             the embedded web build will be silent."
        );
    }
    let mut sounds_lit = String::from("&[");
    for (id, path) in &sounds {
        sounds_lit.push_str(&format!(
            "({id}, include_bytes!(r\"{}\")), ",
            path.display()
        ));
    }
    sounds_lit.push(']');

    let code = format!(
        "// @generated by build.rs — embedded original data (personal use).\n\
         pub static MAP: &[u8] = include_bytes!(r\"{}\");\n\
         pub static DATA: &[u8] = include_bytes!(r\"{}\");\n\
         pub static SOUNDS: &[(u16, &[u8])] = {};\n",
        map_path.display(),
        data_path.display(),
        sounds_lit,
    );
    fs::write(&out, code).expect("write embedded_data.rs");
}
