// SPDX-License-Identifier: GPL-3.0-or-later
//! The original data embedded into the binary (the optional `embed-data` feature),
//! producing a self-contained build that runs without `--data`.
//!
//! The bytes are generated by `build.rs` from `WILSON_EMBED_DATA` at build time; they
//! are never stored in the repository. Parsing happens in memory — no temp files.

use wilson_dgds::{Archive, Palette};

// `MAP`, `DATA` and `SOUNDS` are generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/embedded_data.rs"));

/// Parse the embedded archive and its palette.
pub fn archive_and_palette() -> (Archive, Palette) {
    let archive = Archive::parse(MAP, DATA).expect("embedded RESOURCE data parses");
    let palette = archive
        .palette()
        .cloned()
        .expect("embedded data has a palette");
    (archive, palette)
}

/// The embedded sound effects, indexed by id (`0..25`), for [`crate::audio::Audio`].
pub fn sound_bytes() -> Vec<Option<Vec<u8>>> {
    let mut sounds = vec![None; 25];
    for &(id, bytes) in SOUNDS {
        if let Some(slot) = sounds.get_mut(id as usize) {
            *slot = Some(bytes.to_vec());
        }
    }
    sounds
}
